### ISSUE TITLE
Possible Swag: Cups

### ISSUE THREAD

**Issue by RichiH** [promcon/orga#3]
* https://www.werbemittel24.com/glas-sri-lanka.html
* https://www.werbemittel24.com/tasse-henkelbecher.html

**Comment by juliusv** [comment]
Nice. I think I like https://www.werbemittel24.com/glas-sri-lanka.html more due to its slightly conical (rather than just cylindrical) shape.

My vote for having those with just a Prometheus logo and nothing else :) That'd look really cool!

**Comment by matthiasr** [comment]
I like the Henkelbecher better because it's cylindrical 😄  Not a strong preference though.

**Comment by RichiH** [comment]
Upper one is 404, I also prefer the more "normal" one.
